project 'msgCarrierDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!
install!'cocoapods',:deterministic_uuids=>false

target 'msgCarrierDemo' do

    pod 'msgCarrier'
end
